[project]
name = "web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "himanshuchandrakar465", email = "himanshuchandrakar465@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.17",
    "ruff>=0.16.7",
]

[project.scripts]
web = "web:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
